### PR TITLE
Add ocaml relay

### PR DESCRIPTION
**Pull request by reynir**
This is a mostly direct translation of relay.c. I have only tested it insofar as it creates a tap device and goes into a loop. I have not tested that any packets are copied (I didn't know how to off-hand).

### CODE REVIEW

**Comment by palainp** [comment]
Thank you!

I ran into an issue with ocaml 4.14.2 switch:
```
File "dune", line 4, characters 37-49:
4 |   (foreign_stubs (language c) (names tuntap_stubs))
                                         ^^^^^^^^^^^^
tuntap_stubs.c: In function ‘tuntap_create_tap_interface’:
tuntap_stubs.c:23:9: error: implicit declaration of function ‘caml_uerror’ [-Wimplicit-function-declaration]
   23 |         caml_uerror("open", Nothing);
      |         ^~~~~~~~~~~
```
But it worked with my ocaml 5.2 switch, so maybe I missed a package or have an outdated switch :(

Then I tried out `relay.exe` but I failed to run it correctly, it doesn't show any message at startup:
```
$ ./_build/default/relay.exe input output

```

**Comment by palainp** [comment]
And for testing locally I run with linux:
```bash
$ sudo bash misc/setup_network.sh
net.ipv4.ip_forward = 0
net.ipv4.conf.all.arp_announce = 1
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.accept_local = 1
$ cd misc/ocaml && dune build && ./_build/default/relay.exe input output
```

EDIT: and in two other terminals: `iperf3 -s -p 7070 --bind-dev input` and `iperf3 -c 10.10.0.100 --bind-dev output -p 7070`

**Comment by palainp** [comment]
Oh I spoke too fast, it seems the packets are correctly going from one interface to the other, but something is failing with my iperf3 server, the SYN packet has no reply.

**Comment by reynir** [comment]
> I ran into an issue with ocaml 4.14.2 switch:
> 
> ```
> File "dune", line 4, characters 37-49:
> 4 |   (foreign_stubs (language c) (names tuntap_stubs))
>                                          ^^^^^^^^^^^^
> tuntap_stubs.c: In function ‘tuntap_create_tap_interface’:
> tuntap_stubs.c:23:9: error: implicit declaration of function ‘caml_uerror’ [-Wimplicit-function-declaration]
>    23 |         caml_uerror("open", Nothing);
>       |         ^~~~~~~~~~~
> ```
> 
> But it worked with my ocaml 5.2 switch, so maybe I missed a package or have an outdated switch :(

Yes, sorry, I tested it on OCaml 5. I pushed a change that should fix the uerror error, but there may be more errors.

**Comment by palainp** [comment]
Thank you, I'm fine with Ocaml5.
Regarding my setup, the failure was netfilter that has default to drop policy, once changed I was able to run the tests and I got (first run is ocaml, second run is C relay, and I'm not really confident about the possible bottlenecks as I run it on a Qubes AppVM):
```
$  iperf3 -c 10.10.0.100 --bind-dev output -p 7070
Connecting to host 10.10.0.100, port 7070
[  5] local 10.10.0.200 port 32936 connected to 10.10.0.100 port 7070
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   136 MBytes  1.14 Gbits/sec    0   1.34 MBytes       
[  5]   1.00-2.00   sec  84.6 MBytes   710 Mbits/sec   49   1.13 MBytes       
[  5]   2.00-3.00   sec  81.1 MBytes   681 Mbits/sec    0   1.24 MBytes       
[  5]   3.00-4.00   sec  82.2 MBytes   690 Mbits/sec    0   1.31 MBytes       
[  5]   4.00-5.00   sec  83.2 MBytes   698 Mbits/sec    0   1.37 MBytes       
[  5]   5.00-6.00   sec  84.6 MBytes   710 Mbits/sec    3   1.03 MBytes       
[  5]   6.00-7.00   sec  86.2 MBytes   724 Mbits/sec    0   1.08 MBytes       
[  5]   7.00-8.00   sec  84.9 MBytes   712 Mbits/sec    0   1.13 MBytes       
[  5]   8.00-9.00   sec  80.9 MBytes   678 Mbits/sec    0   1.18 MBytes       
[  5]   9.00-10.00  sec  82.4 MBytes   691 Mbits/sec    0   1.23 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   886 MBytes   744 Mbits/sec   52             sender
[  5]   0.00-10.02  sec   885 MBytes   741 Mbits/sec                  receiver

iperf Done.
$  iperf3 -c 10.10.0.100 --bind-dev output -p 7070
Connecting to host 10.10.0.100, port 7070
[  5] local 10.10.0.200 port 49988 connected to 10.10.0.100 port 7070
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   226 MBytes  1.89 Gbits/sec   55   1.15 MBytes       
[  5]   1.00-2.00   sec   241 MBytes  2.02 Gbits/sec    0   1.30 MBytes       
[  5]   2.00-3.00   sec   199 MBytes  1.67 Gbits/sec    1   1.00 MBytes       
[  5]   3.00-4.00   sec   225 MBytes  1.89 Gbits/sec    0   1.16 MBytes       
[  5]   4.00-5.00   sec   188 MBytes  1.58 Gbits/sec    0   1.27 MBytes       
[  5]   5.00-6.00   sec   200 MBytes  1.68 Gbits/sec    2    995 KBytes       
[  5]   6.00-7.00   sec   206 MBytes  1.73 Gbits/sec    0   1.12 MBytes       
[  5]   7.00-8.00   sec   236 MBytes  1.98 Gbits/sec    0   1.26 MBytes       
[  5]   8.00-9.00   sec   229 MBytes  1.92 Gbits/sec    1    997 KBytes       
[  5]   9.00-10.00  sec   230 MBytes  1.93 Gbits/sec    0   1.14 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  2.13 GBytes  1.83 Gbits/sec   59             sender
[  5]   0.00-10.00  sec  2.13 GBytes  1.83 Gbits/sec                  receiver

iperf Done.
```

**Comment by reynir** [comment]
Here are the numbers I got on a Hetzner VM (not a good setup for testing this). First relay.ml:
```
Connecting to host 10.10.0.100, port 7070
[  5] local 10.10.0.200 port 56076 connected to 10.10.0.100 port 7070
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.01   sec  51.9 MBytes   429 Mbits/sec   44    745 KBytes       
[  5]   1.01-2.00   sec  47.5 MBytes   404 Mbits/sec    0    793 KBytes       
[  5]   2.00-3.00   sec  60.0 MBytes   503 Mbits/sec    0    844 KBytes       
[  5]   3.00-4.00   sec  62.5 MBytes   524 Mbits/sec    0    898 KBytes       
[  5]   4.00-5.01   sec  61.2 MBytes   507 Mbits/sec    0    952 KBytes       
[  5]   5.01-6.00   sec  55.0 MBytes   468 Mbits/sec    0    994 KBytes       
[  5]   6.00-7.00   sec  63.8 MBytes   535 Mbits/sec    0   1.02 MBytes       
[  5]   7.00-8.00   sec  70.0 MBytes   586 Mbits/sec    0   1.07 MBytes       
[  5]   8.00-9.00   sec  67.5 MBytes   567 Mbits/sec    0   1.11 MBytes       
[  5]   9.00-10.00  sec  65.0 MBytes   545 Mbits/sec    0   1.16 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   604 MBytes   507 Mbits/sec   44             sender
[  5]   0.00-10.02  sec   602 MBytes   504 Mbits/sec                  receiver

iperf Done.
```
Then relay.c:
```
Connecting to host 10.10.0.100, port 7070
[  5] local 10.10.0.200 port 58938 connected to 10.10.0.100 port 7070
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  77.9 MBytes   653 Mbits/sec   53   1.09 MBytes       
[  5]   1.00-2.00   sec  80.0 MBytes   671 Mbits/sec    0   1.20 MBytes       
[  5]   2.00-3.00   sec  80.0 MBytes   671 Mbits/sec    0   1.28 MBytes       
[  5]   3.00-4.01   sec  78.8 MBytes   654 Mbits/sec    0   1.35 MBytes       
[  5]   4.01-5.00   sec  85.0 MBytes   720 Mbits/sec    1   1.00 MBytes       
[  5]   5.00-6.00   sec  81.2 MBytes   682 Mbits/sec    0   1.06 MBytes       
[  5]   6.00-7.00   sec  81.2 MBytes   682 Mbits/sec    0   1.11 MBytes       
[  5]   7.00-8.00   sec  77.5 MBytes   650 Mbits/sec    0   1.16 MBytes       
[  5]   8.00-9.00   sec  76.2 MBytes   639 Mbits/sec    0   1.20 MBytes       
[  5]   9.00-10.00  sec  81.2 MBytes   682 Mbits/sec    0   1.25 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   799 MBytes   670 Mbits/sec   54             sender
[  5]   0.00-10.01  sec   797 MBytes   667 Mbits/sec                  receiver

iperf Done.
```

This was with OCaml 5.2.1

**Comment by reynir** [comment]
I managed to compile on 4.14.2:
```
Connecting to host 10.10.0.100, port 7070
[  5] local 10.10.0.200 port 44730 connected to 10.10.0.100 port 7070
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  61.9 MBytes   519 Mbits/sec   57   1.07 MBytes       
[  5]   1.00-2.00   sec  71.2 MBytes   598 Mbits/sec    0   1.19 MBytes       
[  5]   2.00-3.00   sec  68.8 MBytes   577 Mbits/sec    0   1.28 MBytes       
[  5]   3.00-4.00   sec  68.8 MBytes   577 Mbits/sec    0   1.34 MBytes       
[  5]   4.00-5.00   sec  71.2 MBytes   598 Mbits/sec    2   1022 KBytes       
[  5]   5.00-6.00   sec  72.5 MBytes   608 Mbits/sec    0   1.06 MBytes       
[  5]   6.00-7.00   sec  75.0 MBytes   630 Mbits/sec    0   1.10 MBytes       
[  5]   7.00-8.00   sec  78.8 MBytes   661 Mbits/sec    0   1.14 MBytes       
[  5]   8.00-9.00   sec  68.8 MBytes   576 Mbits/sec    0   1.18 MBytes       
[  5]   9.00-10.00  sec  66.2 MBytes   556 Mbits/sec    0   1.22 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   703 MBytes   590 Mbits/sec   59             sender
[  5]   0.00-10.02  sec   701 MBytes   587 Mbits/sec                  receiver

iperf Done.
```

I think there is just too much noise on that VM for these tests to be worth anything :D you can probably get better results,

**Comment by palainp** [comment]
Ok, thank you! I can merge and continue to test later :)
